-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-23 07:35:00 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE address (
    place_id   INTEGER NOT NULL,
    town       VARCHAR2(50) NOT NULL,
    address    VARCHAR2(128) NOT NULL
);

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( place_id );

ALTER TABLE address ADD CONSTRAINT address_un UNIQUE ( town,
                                                       address );

CREATE TABLE call_911 (
    witness_id         INTEGER NOT NULL,
    operator_pass_id   VARCHAR2(10 CHAR) NOT NULL,
    call_begin         TIMESTAMP NOT NULL,
    call_end           TIMESTAMP
);

ALTER TABLE call_911
    ADD CONSTRAINT call_911_pk PRIMARY KEY (
                                             operator_pass_id,
                                             call_begin );

CREATE TABLE call_center_911 (
    depart_identif_id   INTEGER NOT NULL,
    department_number   INTEGER NOT NULL,
    place_id            INTEGER NOT NULL
);

ALTER TABLE call_center_911 ADD CONSTRAINT call_center_911_pk PRIMARY KEY ( depart_identif_id );

ALTER TABLE call_center_911 ADD CONSTRAINT call_center_911_un UNIQUE ( department_number,
                                                                       place_id );

CREATE TABLE operator_911 (
    operator_pass_id    VARCHAR2(10 CHAR) NOT NULL,
    depart_identif_id   INTEGER NOT NULL
);

ALTER TABLE operator_911 ADD CONSTRAINT operator_911_pk PRIMARY KEY ( operator_pass_id );

CREATE TABLE person (
    passport_id   VARCHAR2(10 CHAR) NOT NULL,
    name          VARCHAR2(200) NOT NULL
);

ALTER TABLE person ADD CONSTRAINT person_pk PRIMARY KEY ( passport_id );

CREATE TABLE phone (
    phone_number VARCHAR2(10 CHAR) NOT NULL
);

ALTER TABLE phone ADD CONSTRAINT phone_pk PRIMARY KEY ( phone_number );

CREATE TABLE phone_owner (
    passport_id    VARCHAR2(10 CHAR) NOT NULL,
    phone_number   VARCHAR2(10 CHAR) NOT NULL,
    data_own       DATE NOT NULL,
    status         CHAR(1) NOT NULL
);

ALTER TABLE phone_owner ADD CONSTRAINT phone_owner_pk PRIMARY KEY ( phone_number,
                                                                    passport_id );

CREATE TABLE town (
    town VARCHAR2(50) NOT NULL
);

ALTER TABLE town ADD CONSTRAINT town_pk PRIMARY KEY ( town );

CREATE TABLE witness_accident (
    witness_id     INTEGER NOT NULL,
    phone_number   VARCHAR2(10 CHAR) NOT NULL,
    place_id       INTEGER NOT NULL,
    title          VARCHAR2(128) NOT NULL
);

ALTER TABLE witness_accident ADD CONSTRAINT witness_accident_pk PRIMARY KEY ( witness_id );

ALTER TABLE witness_accident
    ADD CONSTRAINT witness_accident_un UNIQUE ( place_id,
                                                phone_number,
                                                title );

ALTER TABLE call_center_911
    ADD CONSTRAINT address_fk FOREIGN KEY ( place_id )
        REFERENCES address ( place_id );

ALTER TABLE call_911
    ADD CONSTRAINT call_911_operator_911_fk FOREIGN KEY ( operator_pass_id )
        REFERENCES operator_911 ( operator_pass_id );

ALTER TABLE call_911
    ADD CONSTRAINT call_911_witness_accident_fk FOREIGN KEY ( witness_id )
        REFERENCES witness_accident ( witness_id );

ALTER TABLE operator_911
    ADD CONSTRAINT call_center_911_fk FOREIGN KEY ( depart_identif_id )
        REFERENCES call_center_911 ( depart_identif_id );

ALTER TABLE operator_911
    ADD CONSTRAINT operator_911_person_fk FOREIGN KEY ( operator_pass_id )
        REFERENCES person ( passport_id );

ALTER TABLE witness_accident
    ADD CONSTRAINT phone_fk FOREIGN KEY ( phone_number )
        REFERENCES phone ( phone_number );

ALTER TABLE phone_owner
    ADD CONSTRAINT phone_owner_person_fk FOREIGN KEY ( passport_id )
        REFERENCES person ( passport_id );

ALTER TABLE phone_owner
    ADD CONSTRAINT phone_owner_phone_fk FOREIGN KEY ( phone_number )
        REFERENCES phone ( phone_number );

ALTER TABLE address
    ADD CONSTRAINT town_fk FOREIGN KEY ( town )
        REFERENCES town ( town );

ALTER TABLE witness_accident
    ADD CONSTRAINT witness_address_fk FOREIGN KEY ( place_id )
        REFERENCES address ( place_id );
        
        
-------------------------FOR INSERTING TO CALL_911------------------------------------------
-------FIRST WE NEED TO CREATE A TRIGGER-----------
CREATE TRIGGER call_control_tr BEFORE
    INSERT ON call_911
    FOR EACH ROW
DECLARE
    update_call_begin call_911.call_begin%TYPE;
BEGIN
    update_call_begin := :new.call_begin;
    IF update_call_begin IS NULL THEN
        update_call_begin := sysdate;
    END IF;
    :new.call_begin := update_call_begin;
END;

-------------AND NOW CAN  INSERT-------        
        
